#PES-55
FaculdadeSenaiJoinville/odysseus pull request #16
Opened 2021-06-25 16:54 UTC by englernicolas

Foi adicionado: os tipos de usuário na entidade de usuaŕios

2021-06-26 17:13 UTC, gabrielSBorges approved these changes

2021-06-26 17:13 UTC, gabrielSBorges commented on src/modules/user/enums/user.types.ts
> +export enum UserType {
tem um diretório "modules/user/others", dentro dele você cria "user.type.ts"

2021-06-26 17:13 UTC, gabrielSBorges commented on src/core/database/mysql/entities/user.entity.ts
> +	public type: UserType;
tem que adicionar a tradução pra esse campo lá no odyssey-locale

2021-06-26 17:13 UTC, gabrielSBorges commented on src/modules/auth/auth.controller.ts
> +	public async me(): Promise<User> {
e da uma verificada no swagger se a documentação pra essa api ficou legal mesmo

2021-06-26 17:14 UTC, gabrielSBorges requested changes
Deu erro nos testes também. É interessante sempre aguardar o github actions terminar a execução das tasks pra já dale no meio assim que possível caso dê algo errado

2021-06-27 17:45 UTC, tchiteu approved these changes
Pelo o que eu vi e entendi, tirando as alterações que o Gabs solicitou, está tudo certo.

2021-06-29 03:40 UTC, gabrielSBorges requested changes

2021-06-29 03:40 UTC, gabrielSBorges commented on package.json
> +		"odyssey-dictionary": "^1.3.0",
só remove esse ^

2021-06-29 03:40 UTC, gabrielSBorges commented on package.json
> +		"odyssey-dictionary": "^1.3.0",
sem o ^ a gente ta especificando que queremos usar exatamente essa versão. Pode não ocorrer no nosso caso, mas existem outras formas de publicar uma versão, aí com o ^ o yarn pode acabar pegando a versão que não deveria

2021-06-29 03:40 UTC, gabrielSBorges commented on src/modules/user/dtos/create-user.dto.ts
> +    @ApiProperty({ example: 'ADMIN', description: 'tipo de usuário.' })
'Tipo do usuário.'

2021-07-09 12:56 UTC, gabrielSBorges requested changes

2021-07-09 12:56 UTC, gabrielSBorges commented on src/modules/user/dtos/create-user.dto.ts
> +    @ApiProperty({ example: 'ADMIN', description: 'Tipo de usuário.' })
"do"

2021-07-09 12:57 UTC, gabrielSBorges reviewed
Tem uns warning do github actions, mas não precisa dar bola. São umas duas variáveis que não estão sendo utilizadas, mas não é erro teu

2021-07-10 06:03 UTC, merged