feature(users): creating user listing method #PES-231
FaculdadeSenaiJoinville/odysseus pull request #20
Opened 2021-07-28 00:25 UTC by tchiteu

2021-07-28 02:01 UTC, gabrielSBorges requested changes
Tão brabo, tem nada de errado no teu código, porém existe uma forma "mais correta" de fazer esse trampo que é criando um repository pra users, assim que der nós veremos isso

2021-07-28 02:03 UTC, gabrielSBorges commented
Adiciona a label "code review" no PR sempre que for mandar pra CR
![image](https://user-images.githubusercontent.com/32948255/127251872-ece8c01d-4e9b-42fc-8fb5-f76b2cba43f8.png)

2021-07-28 02:04 UTC, gabrielSBorges commented
E a label "feature" tbm pra indicar que o PR se trata da implementação de uma feature

2021-07-30 00:35 UTC, gabrielSBorges approved these changes

2021-07-30 00:41 UTC, englernicolas approved these changes
Fino do fino

2021-07-30 00:48 UTC, merged