PES-232 - Api de detalhes do usuário
FaculdadeSenaiJoinville/odysseus pull request #21
Opened 2021-08-03 01:02 UTC by tchiteu

Realizei outros ajustes simples relacionados ao usuário.

2021-08-03 01:31 UTC, englernicolas reviewed
Dei umas ideias ali, mas tá aprovado :cat:

2021-08-03 01:31 UTC, englernicolas commented on src/modules/user/users.controller.ts
> +	@Get('list/:id')
será que se fosse apenas '/:id' não seria mais interessante?

2021-08-03 01:31 UTC, englernicolas commented on src/modules/user/users.controller.ts
> +	@Get('/list')
Talvez não precise especificar o '/list', um get no users dá para imaginar que tu vai pegar todos. Um get com /:id da a entender que vai pegar um só, um post no users da pra imaginar que é criação, um posto com o /:id é edição. Fazemos assim lá no trampo.

2021-08-03 01:38 UTC, gabrielSBorges commented on src/modules/user/users.controller.ts
> +	@Get('/list')
a ideia é poder identificar quais apis servem para o que, naquele modelo de backend para frontend, então essa api de listagem não é uma api de listagem genérica, mas sim uma api de listagem para a tela de listagem

2021-08-03 01:40 UTC, gabrielSBorges commented on src/modules/auth/auth.service.ts
> +		}
";"

2021-08-03 02:12 UTC, gabrielSBorges requested changes

2021-08-04 19:44 UTC, gabrielSBorges commented on src/modules/user/users.controller.ts
> +	@Get('list/:id')
acho que esse pode ser "details/:id", já que não se trata do get genérico. Aí no mesmo caso do list, tem que avaliar quais campos essa tem que retornar mesmo, só dar uma olhada na modal de detalhes

2021-08-05 01:50 UTC, gabrielSBorges submitted a review, later dismissed

2021-08-05 02:12 UTC, englernicolas commented on src/modules/user/users.service.ts
> +		this.usersPolicies.mustHasUser(user);
Eu tava pesquisando hoje para colocar, e aparentemente must has não existe, o correto é must have.

2021-08-05 22:43 UTC, tchiteu commented on src/modules/user/users.service.ts
> +		this.usersPolicies.mustHasUser(user);
Brabo, vou arrumar

2021-08-05 23:58 UTC, gabrielSBorges approved these changes

2021-08-06 00:31 UTC, englernicolas approved these changes

2021-08-09 15:30 UTC, merged