PES-234 - Api de desativar usuário
FaculdadeSenaiJoinville/odysseus pull request #24
Opened 2021-08-06 00:27 UTC by englernicolas

2021-08-16 04:56 UTC, gabrielSBorges commented on src/modules/user/specs/users.spec.ts
> +import { FindManyOptions } from 'typeorm';
o linter ta falando que isso aqui não ta sendo utilizado

2021-08-16 22:58 UTC, tchiteu approved these changes

2021-08-16 22:59 UTC, tchiteu requested changes
Só resolver os conflitos.

2021-08-19 22:50 UTC, tchiteu commented on src/modules/user/users.controller.ts
> +		return this.userService.updateStatus(id);
Acho que você deveria criar essa função `updateStatus(id)` no `userRepository` (não tenho certeza)

2021-08-19 23:00 UTC, gabrielSBorges commented on src/modules/user/users.controller.ts
> +		return this.userService.updateStatus(id);
não seria necessário pq ele não faz nenhuma operação especial de banco de dados, é só um find depois um save

2021-08-19 23:03 UTC, gabrielSBorges commented on src/modules/user/users.controller.ts
> +		return this.userService.updateStatus(id);
![image](https://user-images.githubusercontent.com/32948255/130155086-3a59076d-9ae5-4af7-ac6d-504e77afcb0a.png)

2021-08-19 23:37 UTC, tchiteu approved these changes

2021-08-23 22:30 UTC, gabrielSBorges approved these changes

2021-08-24 22:37 UTC, tchiteu approved these changes

2021-08-24 22:38 UTC, merged